name: Build and Publish Docker Image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create tag
        id: tag-generator
        # run: echo "::set-output name=tag::$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        run: echo "tag=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3

      - name: Login dockerhub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v2.2.0
        with:
          file: Dockerfile.debug
          tags: |
            spedenaave/dpg:debug
          push: true
